"""Added Customer odel

Revision ID: 837599d3986e
Revises: efa3beeb24fe
Create Date: 2023-09-13 13:04:26.222970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837599d3986e'
down_revision = 'efa3beeb24fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###
